### PR TITLE
Updating readme

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Anything else we want to add to this, such as a link to the agenda / slides ?

**Comment by dmolsen** [comment]
Not going to have my part of the slides done until tomorrow morning so no point in linking to them now. Sorry.

**Comment by dmolsen** [comment]
Added a link to the Web Design Day edition of Pattern Lab for PHP.

**Comment by bradfrost** [comment]
We shouldn't post the slides. That's always an 11th hour thing :)

**Pull request merged**
